
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luciana
 */
public class JFAluno extends javax.swing.JFrame {

    /**
     * Creates new form JFAluno
     */
    public JFAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBnovo = new javax.swing.JButton();
        jBsalvar = new javax.swing.JButton();
        jBexcluir = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jBsair = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLra = new javax.swing.JLabel();
        jTFra = new javax.swing.JTextField();
        jLnome = new javax.swing.JLabel();
        jTFnome = new javax.swing.JTextField();
        jLemail = new javax.swing.JLabel();
        jTFemail1 = new javax.swing.JTextField();
        jLidade = new javax.swing.JLabel();
        jBprocurar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTFcpf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFrg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFnascimento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFemail2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFdddtel = new javax.swing.JTextField();
        jTFtelefone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFdddcel = new javax.swing.JTextField();
        jTFcelular = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFcep = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFrua = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTFnumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTFbairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTFcidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTFuf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTFobservacao = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTFdataCad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTFsituacao = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTFnome2 = new javax.swing.JTextField();
        jBprocurar2 = new javax.swing.JButton();
        jTFemailpesquisa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jBconsultar = new javax.swing.JButton();
        jBeditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jBnovo.setText("NOVO");
        jBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnovoActionPerformed(evt);
            }
        });

        jBsalvar.setText("SALVAR");
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        jBexcluir.setText("EXCLUIR");
        jBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirActionPerformed(evt);
            }
        });

        jBcancelar.setText("CANCELAR");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jBsair.setText("SAIR");
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLra.setText("RA");
        jPanel1.add(jLra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel1.add(jTFra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 227, -1));

        jLnome.setText("Nome");
        jPanel1.add(jLnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel1.add(jTFnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 390, -1));

        jLemail.setText("Email");
        jPanel1.add(jLemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel1.add(jTFemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 250, -1));

        jLidade.setText("Idade");
        jPanel1.add(jLidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 268, -1, 0));

        jBprocurar.setText("PROCURAR");
        jBprocurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBprocurarActionPerformed(evt);
            }
        });
        jPanel1.add(jBprocurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel1.setText("CPF");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        jPanel1.add(jTFcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 186, -1));

        jLabel2.setText("RG");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));
        jPanel1.add(jTFrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 192, -1));

        jLabel3.setText("Data Nasc");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 60, 10));
        jPanel1.add(jTFnascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 130, -1));

        jLabel4.setText("Email 2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jTFemail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFemail2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTFemail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 320, -1));

        jLabel5.setText("Telefone");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel1.add(jTFdddtel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 46, -1));
        jPanel1.add(jTFtelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 142, -1));

        jLabel6.setText("Celular");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));
        jPanel1.add(jTFdddcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 48, -1));
        jPanel1.add(jTFcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 175, -1));

        jLabel7.setText("Cep");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        jPanel1.add(jTFcep, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 208, -1));

        jLabel8.setText("Rua");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        jPanel1.add(jTFrua, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 420, -1));

        jLabel9.setText("Número");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));
        jPanel1.add(jTFnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 47, -1));

        jLabel10.setText("Bairro");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
        jPanel1.add(jTFbairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 270, -1));

        jLabel11.setText("Cidade");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));
        jPanel1.add(jTFcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 210, -1));

        jLabel12.setText("UF");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, -1, -1));
        jPanel1.add(jTFuf, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 44, -1));

        jLabel13.setText("Observação");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));
        jPanel1.add(jTFobservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 550, -1));

        jLabel14.setText("Data Cadastro");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));
        jPanel1.add(jTFdataCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 142, -1));

        jLabel15.setText("Situação");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));
        jPanel1.add(jTFsituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 235, -1));

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RA", "NOME", "EMAIL"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, 676, 237));

        jTFnome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnome2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTFnome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, -1));

        jBprocurar2.setText("PROCURAR");
        jBprocurar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBprocurar2ActionPerformed(evt);
            }
        });
        jPanel2.add(jBprocurar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        jTFemailpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFemailpesquisaActionPerformed(evt);
            }
        });
        jPanel2.add(jTFemailpesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 270, 20));

        jLabel16.setText("Busca por nome");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel17.setText("Busca por email");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jTabbedPane1.addTab("Consulta", jPanel2);

        jBconsultar.setText("CONSULTAR");
        jBconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconsultarActionPerformed(evt);
            }
        });

        jBeditar.setText("EDITAR");
        jBeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBnovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBsalvar)
                        .addGap(38, 38, 38)
                        .addComponent(jBeditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBconsultar)
                        .addGap(47, 47, 47)
                        .addComponent(jBexcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBcancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBsair))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBnovo)
                    .addComponent(jBsalvar)
                    .addComponent(jBexcluir)
                    .addComponent(jBcancelar)
                    .addComponent(jBsair)
                    .addComponent(jBconsultar)
                    .addComponent(jBeditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparCampos(){
        jTFra.setText("");
        jTFnome.setText("");
        jTFcpf.setText("");
        jTFrg.setText(""); 
        jTFnascimento.setText("");          
        jTFemail1.setText("");
        jTFemail2.setText("");
        jTFdddtel.setText("");
        jTFtelefone.setText("");
        jTFdddcel.setText("");
        jTFcelular.setText("");                
        jTFrua.setText("");
        jTFnumero.setText("");             
        jTFbairro.setText("");
        jTFcep.setText("");
        jTFcidade.setText("");
        jTFuf.setText("");
        jTFobservacao.setText("");
        jTFdataCad.setText("");
        jTFsituacao.setText("");
        
        
        ((DefaultTableModel) jTable1.getModel()).setNumRows(0);  // redefine a tabela com zero linhas
        jTable1.updateUI();  // Atualiza a tabela (na tela)
        
        jTabbedPane1.setSelectedIndex(0); // ativa a primeira guia
        
        
    }
    
    private void carregarFormulario(Aluno a){  // Setar os demais "campos" da tela
        jTFra.setText( a.getRa() );
        jTFnome.setText( a.getNome() );
        jTFcpf.setText(a.getCpf());
        jTFrg.setText(a.getRg()); 
        jTFnascimento.setText(a.getDataNas());        
        jTFemail1.setText(a.getEmail1());
        jTFemail2.setText(a.getEmail2());
        jTFdddtel.setText(a.getDddTel());
        jTFtelefone.setText(a.getTel());
        jTFdddcel.setText(a.getDddCel());
        jTFcelular.setText(a.getCel());                
        jTFrua.setText(a.getRua());
        jTFnumero.setText(String.valueOf(a.getNumero()));             
        jTFbairro.setText(a.getBairro());
        jTFcep.setText(a.getCep());
        jTFcidade.setText(a.getCidade());
        jTFuf.setText(a.getUf());
        jTFobservacao.setText(a.getObs());
        jTFdataCad.setText(a.getDataCadastro());
        jTFsituacao.setText(a.getSituacao());
         
        
    } 
    
    
    
    private void botoes(boolean novo, boolean salvar, boolean consultar, boolean excluir) {
        jBnovo.setEnabled(novo);
        jBsalvar.setEnabled(salvar);
        jBconsultar.setEnabled(consultar);
        jBexcluir.setEnabled(excluir);
    
    }
    
    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        
        Aluno alu;
        alu = new Aluno();
        
                
        alu.setRa(jTFra.getText());        
        alu.setCpf(jTFcpf.getText());
        alu.setRg(jTFrg.getText());
        alu.setNome(jTFnome.getText());
        alu.setDataNas(jTFnascimento.getText());
        alu.setEmail1(jTFemail1.getText());
        alu.setEmail2(jTFemail2.getText());
        alu.setDddTel(jTFdddtel.getText());
        alu.setTel(jTFtelefone.getText());
        alu.setDddCel(jTFdddcel.getText());
        alu.setCel(jTFcelular.getText());
        alu.setRua(jTFrua.getText());
        alu.setNumero( Integer.parseInt(jTFnumero.getText() ) );
        alu.setBairro(jTFbairro.getText());
        alu.setCep(jTFcep.getText());
        alu.setCidade(jTFcidade.getText());
        alu.setUf(jTFuf.getText());
        alu.setObs(jTFobservacao.getText());
        alu.setDataCadastro(jTFdataCad.getText());
        alu.setSituacao(jTFsituacao.getText());
        
        
        AlunoDAO bd;
        bd = new AlunoDAO();
        
        bd.adicionarAluno(alu);
        
//        jTFra.setText("");
//        jTFnome.setText("");
//        jTFemail.setText("");
//        jTFidade.setText("");
          limparCampos();
          
          botoes(true, false, true, false);
                
        
    }//GEN-LAST:event_jBsalvarActionPerformed

    
    
    
    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        
        
//        jTFra.setText("");
//        jTFnome.setText("");
//        jTFemail.setText("");
//        jTFidade.setText("");
          limparCampos();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBprocurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBprocurarActionPerformed
        
        AlunoDAO bd;
        bd = new AlunoDAO();
        
        Aluno alu;
        alu = new Aluno();
        
        alu = bd.consultaAlunoPorRA(jTFra.getText());
        
        if(alu != null){
            
            JOptionPane.showMessageDialog(null, alu.getNome() + " já cadastrado");
            
            jTFra.setText( alu.getRa() );
            jTFnome.setText( alu.getNome() );
            jTFcpf.setText(alu.getCpf());
            jTFrg.setText(alu.getRg()); 
            jTFnascimento.setText(alu.getDataNas());        
            jTFemail1.setText(alu.getEmail1());
            jTFemail2.setText(alu.getEmail2());
            jTFdddtel.setText(alu.getDddTel());
            jTFtelefone.setText(alu.getTel());
            jTFdddcel.setText(alu.getDddCel());
            jTFcelular.setText(alu.getCel());                
            jTFrua.setText(alu.getRua());
            jTFnumero.setText(String.valueOf(alu.getNumero()));             
            jTFbairro.setText(alu.getBairro());
            jTFcep.setText(alu.getCep());
            jTFcidade.setText(alu.getCidade());
            jTFuf.setText(alu.getUf());
            jTFobservacao.setText(alu.getObs());
            jTFdataCad.setText(alu.getDataCadastro());
            jTFsituacao.setText(alu.getSituacao());
            
            
        }
        else{
            botoes(false, true, false, false);
        }
        
    }//GEN-LAST:event_jBprocurarActionPerformed

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
       
        int resposta;
        resposta = JOptionPane.showConfirmDialog(null, "Confirma exclusão");
        
        if(resposta == JOptionPane.YES_OPTION){
            AlunoDAO bd;
            bd = new AlunoDAO();
            bd.excluirAluno(jTFra.getText());
            limparCampos();
        }
        
        
    }//GEN-LAST:event_jBexcluirActionPerformed

    private void jBconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsultarActionPerformed
        jTabbedPane1.setSelectedIndex(1);//Ativa a segunda guia
        jTFnome2.requestFocus();//posiciona o cursor na caixa de texto
    }//GEN-LAST:event_jBconsultarActionPerformed

    private void jBprocurar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBprocurar2ActionPerformed
        List <Aluno> listaAluno;
        
        AlunoDAO dao;
        dao = new AlunoDAO();
        
        Aluno alu;
       
        listaAluno = null;
        
    if(!jTFnome2.getText().isBlank()){
           listaAluno = dao.consultarAlunoPorNome(jTFnome2.getText());
        }
    else {
            if(!jTFemailpesquisa.getText().isBlank()){
                 listaAluno = dao.consultarAlunoPorEmail2(jTFemailpesquisa.getText());
         }
            
    }       
                       
        
               
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
        
        for (int y = 0; y < listaAluno.size(); y++) {
            alu = listaAluno.get(y);
            //JOptionPane.showMessageDialog(null, y + " - " + alu.getNome());
           model.addRow(new Object[] {alu.getRa(),alu.getNome(), alu.getEmail1()});
                                       
        }      
    }//GEN-LAST:event_jBprocurar2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String sRa;
        sRa = (String) jTable1.getModel().getValueAt(  jTable1.getSelectedRow(),0  );  // recupera o RA da linha selecionada - coluna zero
        AlunoDAO dao;
        dao = new AlunoDAO();
        
        Aluno a;
        a = new Aluno();
        a = dao.consultaAlunoPorRA(sRa);
        
        carregarFormulario(a);
        
        ((DefaultTableModel) jTable1.getModel()).setNumRows(0);   // redefine a tabela com "zero linhas"
        jTable1.updateUI();  // Atualiza a tabela (na tela)
        jTabbedPane1.setSelectedIndex(0);  // ativa a segunda guia
        
        
        
        botoes(false, false, true, true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
        dispose();
    }//GEN-LAST:event_jBsairActionPerformed

    private void jBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnovoActionPerformed
         jTabbedPane1.setSelectedIndex(0);   // ativa a primeira guia
         jTFra.requestFocus();   // Posiciona o cursor na caixa de texto "jTFra".
    }//GEN-LAST:event_jBnovoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        botoes(true, false, true, false);
    }//GEN-LAST:event_formWindowActivated

    private void jTFemail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFemail2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFemail2ActionPerformed

    private void jTFnome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnome2ActionPerformed

    private void jTFemailpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFemailpesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFemailpesquisaActionPerformed

    private void jBeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditarActionPerformed
        
        Aluno alu;
        alu = new Aluno();
        
                
        alu.setRa(jTFra.getText());        
        alu.setCpf(jTFcpf.getText());
        alu.setRg(jTFrg.getText());
        alu.setNome(jTFnome.getText());
        alu.setDataNas(jTFnascimento.getText());
        alu.setEmail1(jTFemail1.getText());
        alu.setEmail2(jTFemail2.getText());
        alu.setDddTel(jTFdddtel.getText());
        alu.setTel(jTFtelefone.getText());
        alu.setDddCel(jTFdddcel.getText());
        alu.setCel(jTFcelular.getText());
        alu.setRua(jTFrua.getText());
        alu.setNumero( Integer.parseInt(jTFnumero.getText() ) );
        alu.setBairro(jTFbairro.getText());
        alu.setCep(jTFcep.getText());
        alu.setCidade(jTFcidade.getText());
        alu.setUf(jTFuf.getText());
        alu.setObs(jTFobservacao.getText());
        alu.setDataCadastro(jTFdataCad.getText());
        alu.setSituacao(jTFsituacao.getText());
        
        
        AlunoDAO bd;
        bd = new AlunoDAO();
        
        bd.editarAluno(alu);
        
//        jTFra.setText("");
//        jTFnome.setText("");
//        jTFemail.setText("");
//        jTFidade.setText("");
          limparCampos();
          
          botoes(true, false, true, false);
    }//GEN-LAST:event_jBeditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBconsultar;
    private javax.swing.JButton jBeditar;
    private javax.swing.JButton jBexcluir;
    private javax.swing.JButton jBnovo;
    private javax.swing.JButton jBprocurar;
    private javax.swing.JButton jBprocurar2;
    private javax.swing.JButton jBsair;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLemail;
    private javax.swing.JLabel jLidade;
    private javax.swing.JLabel jLnome;
    private javax.swing.JLabel jLra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFbairro;
    private javax.swing.JTextField jTFcelular;
    private javax.swing.JTextField jTFcep;
    private javax.swing.JTextField jTFcidade;
    private javax.swing.JTextField jTFcpf;
    private javax.swing.JTextField jTFdataCad;
    private javax.swing.JTextField jTFdddcel;
    private javax.swing.JTextField jTFdddtel;
    private javax.swing.JTextField jTFemail1;
    private javax.swing.JTextField jTFemail2;
    private javax.swing.JTextField jTFemailpesquisa;
    private javax.swing.JTextField jTFnascimento;
    private javax.swing.JTextField jTFnome;
    private javax.swing.JTextField jTFnome2;
    private javax.swing.JTextField jTFnumero;
    private javax.swing.JTextField jTFobservacao;
    private javax.swing.JTextField jTFra;
    private javax.swing.JTextField jTFrg;
    private javax.swing.JTextField jTFrua;
    private javax.swing.JTextField jTFsituacao;
    private javax.swing.JTextField jTFtelefone;
    private javax.swing.JTextField jTFuf;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
